### ISSUE TITLE
没有声音呀

### ISSUE THREAD

**Issue by yesyet** [hongcyu/char_painting#5]
希望添加，谢谢

**Comment by hongcyu** [comment]
目前还不懂怎么不通过第三方软件提取音频，希望有小伙伴可以帮忙完善音频添加的功能和视频容量大小的优化

**Comment by rollingQP** [comment]
> 希望添加，谢谢
@yesyet 已经添加了，但是得通过第三方的ffmpeg。不过幸好ffmpeg在各平台安装都比较方便，所以应该没什么问题。

**Comment by rollingQP** [comment]
> 希望添加，谢谢
@yesyet 已经添加了，但是得通过第三方的ffmpeg。不过幸好ffmpeg在各平台安装都比较方便，所以应该没什么问题。
